### 图像平滑

In [2]:
import matplotlib.pyplot as plt
import cv2

In [8]:
img_7mvp = cv2.imread('7mvp.jpeg')
cv2.imshow('result', img_7mvp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# 均值滤波
# 简单的平均卷积处理, 像素所在位置的(3,3)矩阵进行求均值
blur = cv2.blur(img_7mvp, (3, 3))
cv2.imshow('result', blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# 方框滤波
# 基本和均值滤波一样，可以选择归一化
# -1 表示和原通道值一样，不需要改  (3,3)是卷积核，normalize: True 做归一化(超过255取余,此时和均值滤波效果一致) False不做归一化(超过255取255)
box = cv2.boxFilter(img_7mvp, -1, (3, 3), normalize=True)
cv2.imshow('result', box)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
box = cv2.boxFilter(img_7mvp, -1, (3, 3), normalize=False)
cv2.imshow('result', box)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 高斯滤波
# 越近的权重越大，越远权重越小
aussian = cv2.GaussianBlur(img_7mvp, (3, 3), 2)
cv2.imshow('result', aussian)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# 中值滤波, 使用中值替代
median = cv2.medianBlur(img_7mvp, 3)
cv2.imshow('result', median)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
import numpy as np

In [21]:
res = np.hstack((blur, aussian, median))
print(res)
cv2.imshow('result', res)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[240 212 217]
  [236 214 217]
  [224 215 216]
  ...
  [207 201 212]
  [204 201 212]
  [204 201 212]]

 [[237 216 220]
  [231 216 218]
  [227 224 225]
  ...
  [249 247 254]
  [207 203 212]
  [204 201 212]]

 [[221 218 219]
  [224 226 226]
  [228 240 238]
  ...
  [253 250 254]
  [248 248 251]
  [204 203 212]]

 ...

 [[232 231 235]
  [230 231 234]
  [247 250 252]
  ...
  [253 253 253]
  [251 251 251]
  [192 192 192]]

 [[219 217 221]
  [220 218 221]
  [232 230 232]
  ...
  [251 251 251]
  [192 192 192]
  [192 192 192]]

 [[220 217 221]
  [221 218 221]
  [233 229 232]
  ...
  [192 192 192]
  [192 192 192]
  [192 192 192]]]


### 形态学-腐蚀操作

In [23]:
img = cv2.imread("黑白色小图.png")
cv2.imshow('result', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
# 腐蚀操作主要用于仅有两种像素点的图片的操作，在卷积核中，如果一部分是黑的，另一部分是白色的，会置为黑色，就是说一个白点变为了黑点
# iterations 是迭代次数，就是说腐蚀了多少次
kernel = np.ones((3,3), np.uint8)
erosion = cv2.erode(img, kernel, iterations=1)
cv2.imshow('result', erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
erosion2 = cv2.erode(img, kernel, iterations=2)
cv2.imshow('result', erosion2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 形态学-膨胀操作

In [27]:
# 腐蚀操作之后会会将图片边缘腐蚀，膨胀操作可以还原
dilate = cv2.dilate(erosion, kernel, iterations=1)
cv2.imshow('result', dilate)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
dilate = cv2.dilate(erosion, kernel, iterations=6)
cv2.imshow('result', dilate)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 开运算和闭运算

In [32]:
# 开： 先腐蚀，后膨胀
img = cv2.imread('黑白色小图.png')

kernel = np.ones((3,3), np.uint8)
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

cv2.imshow('result', opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
# 闭： 先膨胀，再腐蚀
img = cv2.imread('黑白色小图.png')

kernel = np.ones((3,3), np.uint8)
opening = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

cv2.imshow('result', opening)
cv2.waitKey(0)
cv2.destroyAllWindows()