### 图像平滑

In [1]:
import matplotlib.pyplot as plt
import cv2

In [8]:
img_7mvp = cv2.imread('7mvp.jpeg')
cv2.imshow('result', img_7mvp)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# 均值滤波
# 简单的平均卷积处理, 像素所在位置的(3,3)矩阵进行求均值
blur = cv2.blur(img_7mvp, (3, 3))
cv2.imshow('result', blur)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# 方框滤波
# 基本和均值滤波一样，可以选择归一化
# -1 表示和原通道值一样，不需要改  (3,3)是卷积核，normalize: True 做归一化(超过255取余,此时和均值滤波效果一致) False不做归一化(超过255取255)
box = cv2.boxFilter(img_7mvp, -1, (3, 3), normalize=True)
cv2.imshow('result', box)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
box = cv2.boxFilter(img_7mvp, -1, (3, 3), normalize=False)
cv2.imshow('result', box)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 高斯滤波
# 越近的权重越大，越远权重越小
aussian = cv2.GaussianBlur(img_7mvp, (3, 3), 2)
cv2.imshow('result', aussian)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# 中值滤波, 使用中值替代
median = cv2.medianBlur(img_7mvp, 3)
cv2.imshow('result', median)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import numpy as np

In [21]:
res = np.hstack((blur, aussian, median))
print(res)
cv2.imshow('result', res)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[240 212 217]
  [236 214 217]
  [224 215 216]
  ...
  [207 201 212]
  [204 201 212]
  [204 201 212]]

 [[237 216 220]
  [231 216 218]
  [227 224 225]
  ...
  [249 247 254]
  [207 203 212]
  [204 201 212]]

 [[221 218 219]
  [224 226 226]
  [228 240 238]
  ...
  [253 250 254]
  [248 248 251]
  [204 203 212]]

 ...

 [[232 231 235]
  [230 231 234]
  [247 250 252]
  ...
  [253 253 253]
  [251 251 251]
  [192 192 192]]

 [[219 217 221]
  [220 218 221]
  [232 230 232]
  ...
  [251 251 251]
  [192 192 192]
  [192 192 192]]

 [[220 217 221]
  [221 218 221]
  [233 229 232]
  ...
  [192 192 192]
  [192 192 192]
  [192 192 192]]]


### 形态学-腐蚀操作

In [5]:
img = cv2.imread("黑白色小图.png")
cv2.imshow('result', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# 腐蚀操作主要用于仅有两种像素点的图片的操作，在卷积核中，如果一部分是黑的，另一部分是白色的，会置为黑色，就是说一个白点变为了黑点
# iterations 是迭代次数，就是说腐蚀了多少次
kernel = np.ones((3,3), np.uint8)
erosion = cv2.erode(img, kernel, iterations=1)
cv2.imshow('result', erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
erosion2 = cv2.erode(img, kernel, iterations=2)
cv2.imshow('result', erosion2)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 形态学-膨胀操作

In [7]:
# 腐蚀操作之后会会将图片边缘腐蚀，膨胀操作可以还原
dilate = cv2.dilate(erosion, kernel, iterations=1)
cv2.imshow('result', dilate)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'erosion' is not defined

In [8]:
dilate = cv2.dilate(erosion, kernel, iterations=6)
cv2.imshow('result', dilate)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'erosion' is not defined

### 开运算和闭运算

In [11]:
# 开： 先腐蚀，后膨胀
img = cv2.imread('黑白色小图.png')

kernel = np.ones((3,3), np.uint8)
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

cv2.imshow('result', opening)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [12]:
# 闭： 先膨胀，再腐蚀
img = cv2.imread('黑白色小图.png')

kernel = np.ones((3,3), np.uint8)
opening = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

cv2.imshow('result', opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 梯度运算

In [23]:
# 梯度=膨胀-腐蚀, 会去掉相同的部分，剩余边界信息
pie = cv2.imread('黑白色小图.png')
kernel = np.ones((3, 3), np.uint8)
dilate = cv2.dilate(pie, kernel, iterations=1)
erosion = cv2.erode(pie, kernel, iterations=1)

res = np.hstack((dilate, erosion))

cv2.imshow('result', res)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
gradient = cv2.morphologyEx(pie, cv2.MORPH_GRADIENT, kernel)

cv2.imshow('result', gradient)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 礼帽与黑帽

- 礼帽 = 原始输入 - 开运算结果
- 黑帽 = 闭运算 - 原始输入

In [26]:
# 礼帽,  开运算先腐蚀后膨胀，会消除毛刺，礼帽后只剩毛刺了
kernel = np.ones((3, 3), np.uint8)
img = cv2.imread('黑白色小图.png')
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)
cv2.imshow('result', tophat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
# 黑帽, 闭运算先膨胀后腐蚀，会保留毛刺，黑帽之后会剩下原始内容的整体轮廓
kernel = np.ones((7, 7), np.uint8)
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)
cv2.imshow('result', blackhat)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 图像梯度-Sobel算子

  卷积核中左减右，下减上

In [48]:
img = cv2.imread('hb.png', cv2.IMREAD_GRAYSCALE)
cv2.imshow('result', img)
cv2.waitKey()
cv2.destroyAllWindows()

#### dst = cv2.Sobel(src, ddepth, dx, dy, ksize)

- ddepth: 图像的深度
- dx和dy分别表示水平和垂直方向, 1计算 0不计算
- ksize是Sobel算子的大小

In [55]:
def cv_show(name, img):
    cv2.imshow(name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [56]:
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
cv_show('result',sobelx)

白到黑是正数，黑到白就是负数了，所有的负数会被截断成0, 所以要取绝对值

In [57]:
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sobelx = cv2.convertScaleAbs(sobelx)
cv_show('result', sobelx)

In [65]:
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
sobely = cv2.convertScaleAbs(sobely)
cv_show('result', sobely)

#### 分别计算x和y，再求和

In [66]:
sobelxy = cv2.addWeighted(sobelx, 0.5, sobely, 0.5, 0)
cv_show('result', sobelxy)

In [60]:
#### 不建议直接计算x和y，分别计算x和y然后加和效果比较好 

In [61]:
sobelxy = cv2.Sobel(img,cv2.CV_64F, 1, 1, ksize=3)
cv_show('result', sobelxy)

In [67]:
img = cv2.imread('hb.png', cv2.IMREAD_GRAYSCALE)
sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sobelx = cv2.convertScaleAbs(sobelx)
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
sobely = cv2.convertScaleAbs(sobely)
sobelxy = cv2.addWeighted(sobelx, 0.5, sobely, 0.5, 0)
cv_show('result', sobelxy)

In [68]:
img = cv2.imread('hb.png', cv2.IMREAD_GRAYSCALE)

sobelxy = cv2.Sobel(img, cv2.CV_64F, 1, 1, ksize=3)
sobelxy = cv2.convertScaleAbs(sobelxy)
cv_show('result', sobelxy)

## 图像梯度-Scharr算子

    计算方法和Sobel一致，只是比Sobel更明显一些, 一些Sobel不计算的地方也能显示出来
    
## 图像梯度-laplacian算子-一般不单独使用

    二阶导数。。。。不懂
    计算方法-边缘点(上下左右) - 4 * 中心点

In [75]:
img = cv2.imread('黑白色小图.png', cv2.IMREAD_GRAYSCALE)


sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sobelx = cv2.convertScaleAbs(sobelx)
sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
sobely = cv2.convertScaleAbs(sobely)
sobelxy = cv2.addWeighted(sobelx, 0.5, sobely, 0.5, 0)


scharrx = cv2.Scharr(img, cv2.CV_64F, 1, 0)
scharrx = cv2.convertScaleAbs(scharrx)
scharry = cv2.Scharr(img, cv2.CV_64F, 0, 1)
scharry = cv2.convertScaleAbs(scharrx)
scharrxy = cv2.addWeighted(scharrx, 0.5, scharry, 0.5, 0)

laplacian = cv2.Laplacian(img, cv2.CV_64F)
laplacian = cv2.convertScaleAbs(laplacian)

res = np.hstack((img, sobelxy, scharrxy, laplacian))
cv_show('result', res)


## Canny边缘检测

- 1) 使用高斯滤波，以平滑图像，滤除噪声
- 2) 计算图像中每个像素点的梯度强度和方向。(使用的是Sobel算子)
- 3) 应用非极大值抑制，以消除边缘检测带来的杂散响应
- 4) 应用双阈值检测来确定真实的和潜在的边缘
- 5) 通过抑制孤立的弱边缘最终完成边缘检测